# Generated by Django 2.2.4 on 2019-08-21 06:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=200, verbose_name='Website Name')),
                ('app_title', models.CharField(max_length=200, verbose_name='Website Title (60 Characters Long)')),
                ('app_keywords', models.TextField(blank=True, null=True, verbose_name='Website Keywords (Separated by Commas)')),
                ('app_description', models.TextField(blank=True, null=True, verbose_name='Website Description (160 Characters Long)')),
                ('app_email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Primary Email for Website')),
                ('app_contact', models.CharField(blank=True, max_length=15, null=True, verbose_name='Contact Number for Website')),
                ('app_address', models.TextField(blank=True, null=True, verbose_name='Physical Address for the Website')),
                ('app_postal', models.CharField(max_length=10, null=True, verbose_name='Postal Address for the Website')),
                ('app_created_at', models.DateTimeField(auto_now_add=True, verbose_name='App Created Date')),
                ('app_updated_at', models.DateTimeField(auto_now=True, verbose_name='App Updated Date')),
            ],
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('socialmedia_title', models.CharField(max_length=20, verbose_name='Social Media Name')),
                ('socialmedia_url', models.URLField(max_length=150, verbose_name='Social Media URL')),
                ('socialmedia_icon', models.CharField(max_length=200, verbose_name='Social Media Icon')),
                ('socialmedia_craeted_at', models.DateTimeField(auto_now_add=True, verbose_name='Social Media Created Date')),
                ('socialmedia_updated_at', models.DateTimeField(auto_now=True, verbose_name='Social Media Updated Date')),
                ('socialmedia_added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Social Media Added By')),
            ],
        ),
    ]
