# Generated by Django 2.2.4 on 2019-08-21 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thisapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appdetail',
            name='app_postal',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Postal Address for the Website'),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='socialmedia_icon',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Social Media Icon'),
        ),
    ]
