# Generated by Django 2.2.4 on 2019-08-21 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thisapp', '0002_auto_20190821_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmedia',
            name='socialmedia_is_active',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='Yes', max_length=10, verbose_name='Is Active?'),
        ),
    ]
