# Generated by Django 2.2.4 on 2019-08-21 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thisapp', '0003_socialmedia_socialmedia_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='appdetail',
            name='app_logo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Website Logo'),
        ),
    ]
