# Generated by Django 2.2.4 on 2019-08-15 17:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tour', '0002_auto_20190815_2231'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_title', models.CharField(max_length=200, verbose_name='Tour Title')),
                ('tour_slug', models.CharField(max_length=200, verbose_name='Tour Slug')),
                ('tour_duration', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Tour Duration')),
                ('tour_altitude', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Tour Max Altitude')),
                ('tour_difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='Medium', max_length=10, verbose_name='Tour Difficulty')),
                ('tour_description', models.TextField(blank=True, null=True, verbose_name='Tour Description')),
                ('tour_image', models.ImageField(blank=True, null=True, upload_to='tours/', verbose_name='Tour Image')),
                ('tour_is_active', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='Yes', max_length=10, verbose_name='Is Active?')),
                ('tour_is_featured', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='Yes', max_length=10, verbose_name='Is Featured?')),
                ('tour_created_at', models.DateTimeField(auto_now_add=True, verbose_name='Added Date')),
                ('tour_updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('seo_tour_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='SEO Tour Title (60 Characters Long)')),
                ('seo_tour_keywords', models.TextField(blank=True, null=True, verbose_name='SEO Tour Keywords Separated by Commas')),
                ('seo_tour_description', models.TextField(blank=True, null=True, verbose_name='SEO Tour Description (160 Characters Long)')),
                ('tour_activity', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tour.Activity', verbose_name='Tour Activity')),
                ('tour_added_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Added By')),
                ('tour_region', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tour.Region', verbose_name='Tour Region')),
            ],
        ),
    ]
