# Generated by Django 2.2.4 on 2019-08-15 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0003_tour'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='tour_map',
            field=models.ImageField(blank=True, null=True, upload_to='maps/', verbose_name='Tour Map'),
        ),
    ]
