# Generated by Django 2.2.4 on 2019-08-15 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0004_tour_tour_map'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='tour_region',
        ),
        migrations.AddField(
            model_name='tour',
            name='tour_region',
            field=models.ManyToManyField(to='tour.Region', verbose_name='Tour Region'),
        ),
    ]
