# Generated by Django 3.2.3 on 2024-12-20 06:40

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0006_auto_20190820_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Activity Description'),
        ),
        migrations.AlterField(
            model_name='region',
            name='region_description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Region Description'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='tour_description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Tour Description'),
        ),
    ]
