# Generated by Django 2.2.4 on 2019-08-20 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(max_length=200, verbose_name='Page Title')),
                ('page_slug', models.SlugField(max_length=200, verbose_name='Page Slug')),
                ('page_position', models.CharField(choices=[('top', 'Top'), ('school', 'School'), ('footer', 'Footer')], default='Top', max_length=20, verbose_name='Page Position')),
                ('page_description', models.TextField(blank=True, null=True, verbose_name='Page Description')),
                ('page_image', models.ImageField(blank=True, null=True, upload_to='pages/', verbose_name='Page Image')),
                ('page_is_active', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='Yes', max_length=10, verbose_name='Is Active?')),
                ('page_is_featured', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='Yes', max_length=10, verbose_name='Is Featured?')),
                ('page_created_at', models.DateTimeField(auto_now_add=True, verbose_name='Page Created Date')),
                ('page_updated_at', models.DateTimeField(auto_now=True, verbose_name='Page Updated Date')),
                ('seo_page_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='SEO Page Title (60 Characters Long)')),
                ('seo_page_keywords', models.TextField(blank=True, null=True, verbose_name='SEO Page Keywords (Separated by Commas)')),
                ('seo_page_description', models.TextField(blank=True, null=True, verbose_name='SEO Page Description (160 Characters Long)')),
                ('page_added_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Added By')),
            ],
        ),
    ]
