# Generated by Django 2.2.4 on 2019-08-23 16:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='group_added_at',
            new_name='group_created_at',
        ),
        migrations.AddField(
            model_name='subscriber',
            name='subscriber_created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Added Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscriber',
            name='subscriber_updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated Date'),
        ),
    ]
