# Generated by Django 2.2.4 on 2019-08-20 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_title', models.CharField(max_length=200, verbose_name='Category Title')),
                ('category_slug', models.SlugField(max_length=200, verbose_name='Category Slug')),
                ('category_description', models.TextField(blank=True, null=True, verbose_name='Category Description')),
                ('category_image', models.ImageField(blank=True, null=True, upload_to='categories/')),
                ('category_is_active', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='Yes', max_length=10, verbose_name='Is Active?')),
                ('category_created_at', models.DateTimeField(auto_now_add=True, verbose_name='Category Created Date')),
                ('category_updated_at', models.DateTimeField(auto_now=True, verbose_name='Category Updated Date')),
                ('seo_category_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='SEO Category Title (60 Characters Long)')),
                ('seo_category_keywords', models.TextField(blank=True, null=True, verbose_name='SEO Category Keywords Separated by Commas')),
                ('seo_category_description', models.TextField(blank=True, null=True, verbose_name='SEO Category Description (160 Characters Long)')),
                ('category_added_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Added By')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=200, verbose_name='Post Title')),
                ('post_slug', models.CharField(max_length=200, verbose_name='Post Slug')),
                ('post_description', models.TextField(blank=True, null=True, verbose_name='Post Description')),
                ('post_image', models.ImageField(blank=True, null=True, upload_to='posts/', verbose_name='Post Image')),
                ('post_is_active', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='Yes', max_length=10, verbose_name='Is Active?')),
                ('post_is_featured', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='Yes', max_length=10, verbose_name='Is Featured?')),
                ('post_created_at', models.DateTimeField(auto_now_add=True, verbose_name='Post Created Date')),
                ('post_updated_at', models.DateTimeField(auto_now=True, verbose_name='Post Updated Date')),
                ('seo_post_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='SEO Post Title (60 Characters Long)')),
                ('seo_post_keywords', models.TextField(blank=True, null=True, verbose_name='SEO Post Keywords (Separated by Commas)')),
                ('seo_post_description', models.TextField(blank=True, null=True, verbose_name='SEO Post Description (160 Characters Long)')),
                ('post_added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Added By')),
                ('post_category', models.ManyToManyField(to='blog.Category', verbose_name='Post Category')),
            ],
        ),
    ]
