# Generated by Django 2.2.4 on 2019-08-20 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=200, verbose_name='Blog Title')),
                ('blog_slug', models.CharField(max_length=200, verbose_name='Blog Slug')),
                ('blog_description', models.TextField(blank=True, null=True, verbose_name='Blog Description')),
                ('blog_image', models.ImageField(blank=True, null=True, upload_to='blogs/', verbose_name='Blog Image')),
                ('blog_is_active', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='Yes', max_length=10, verbose_name='Is Active?')),
                ('blog_is_featured', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='Yes', max_length=10, verbose_name='Is Featured?')),
                ('blog_created_at', models.DateTimeField(auto_now_add=True, verbose_name='Blog Created Date')),
                ('blog_updated_at', models.DateTimeField(auto_now=True, verbose_name='Blog Updated Date')),
                ('seo_blog_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='SEO Blog Title (60 Characters Long)')),
                ('seo_blog_keywords', models.TextField(blank=True, null=True, verbose_name='SEO Blog Keywords (Separated by Commas)')),
                ('seo_blog_description', models.TextField(blank=True, null=True, verbose_name='SEO Blog Description (160 Characters Long)')),
                ('blog_added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Added By')),
                ('blog_category', models.ManyToManyField(to='blog.Category', verbose_name='Blog Category')),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
